services:
  - type: web
    name: college-voting-system
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn college_voting.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
