server {
    listen 80;
    server_name YOUR_PUBLIC_IP_OR_DOMAIN;

    location = /favicon.ico { access_log off; log_not_found off; }
    
    location /static/ {
        root /home/ubuntu/VoteHub;
    }

    location /media/ {
        root /home/ubuntu/VoteHub;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
